# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0004_auto_20171025_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='peak1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak13',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak14',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak15',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak8',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak9',
            field=models.IntegerField(default=0),
        ),
    ]
