# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0007_auto_20171025_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='gOneF',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='gTwoF',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='gZero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='gZeroF',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='lysLoss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='manEight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='manFive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='manNine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='manSeven',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='manSix',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='pyroE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='pyroQ',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='sodiumAdduct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='waterAdduct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak10',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak11',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak12',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak13',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak14',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak15',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak4',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak5',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak6',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak7',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak8',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peak',
            name='peak9',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
